```{r}
rm(list = ls())
library(Rsubread)
library(readxl)
library(vsn)
library(tsne)
library(reshape2)
library(xlsx)
library(ggpubr)
library(knitr)
library(gridExtra)
library(DESeq2)
library(ggplot2)
library(dplyr)
library(ggrepel)
library(PCAtools)
library(ggalt)
library(cowplot)
library(org.Hs.eg.db)
library(AnnotationDbi)
library(ReactomePA)
library(ReactomeContentService4R)
library(tidyverse)
library(enrichplot)
library(DOSE)
library(pheatmap)
library(clusterProfiler)
library(msigdbr)
```
```{r}
H_t2g <- msigdbr(species = "Homo sapiens", category = "H") %>% dplyr::select(gs_name, entrez_gene)
C1_t2g <- msigdbr(species = "Homo sapiens", category = "C1") %>% dplyr::select(gs_name, entrez_gene)
C3_t2g <- msigdbr(species = "Homo sapiens", category = "C3") %>% dplyr::select(gs_name, entrez_gene)
C6_t2g <- msigdbr(species = "Homo sapiens", category = "C6") %>% dplyr::select(gs_name, entrez_gene)
msigdb <- bind_rows(H_t2g, C1_t2g, C3_t2g, C6_t2g)
```

```{r}
validated_genes <- c("ICAM1", "ICAM2", "MMP2", "ITGA2", "CCL3L3", "CX3CL1", "CCL24",
                     "NDP", "DACT2", "KLF8", "RNF43", "SERPINA5", "FGFR2", "BRD4")
```


```{r}
wt_ko_raw <- read_tsv("WT vs. K.O._new.tsv")
wt_ko_tgfb_raw <- read_tsv("WT TGFbeta vs. K.O. TGFbeta_new.tsv")
```

```{r}
wt_ko <- wt_ko_raw %>%
  select("Feature ID", 
         "WT - 16140-0003_S11(GE) - Expression values",
         "WT - 16140-0002_S6(GE) - Expression values",
         "WT - 16140-0001_S1(GE) - Expression values",
         "K.O. - 16140-0004_S16(GE) - Expression values",
         "K.O. - 16140-0005_S20(GE) - Expression values",
         "K.O. - 16140-0006_S24(GE) - Expression values",
         "K.O. - 16140-0007_S28(GE) - Expression values",
         "K.O. - 16140-0008_S32(GE) - Expression values",
         "K.O. - 16140-0009_S2(GE) - Expression values")
```

```{r}
wt_ko_tgfb <- wt_ko_tgfb_raw %>%
  select("Feature ID", 
         "WT TGFbeta - 16140-0015_S29(GE) - Expression values",
         "WT TGFbeta - 16140-0014_S25(GE) - Expression values",
         "WT TGFbeta - 16140-0013_S21(GE) - Expression values",
         "K.O. TGFbeta - 16140-0021_S22(GE) - Expression values",
         "K.O. TGFbeta - 16140-0020_S18(GE) - Expression values",
         "K.O. TGFbeta - 16140-0019_S13(GE) - Expression values",
         "K.O. TGFbeta - 16140-0018_S8(GE) - Expression values",
         "K.O. TGFbeta - 16140-0017_S3(GE) - Expression values",
         "K.O. TGFbeta - 16140-0016_S33(GE) - Expression values")
```

```{r}
rawtable <- merge(wt_ko, wt_ko_tgfb, by="Feature ID")
rcounts <- rawtable[,-1]
rownames(rcounts) <- rawtable[,1] 
```

```{r}
cnt <- rcounts[(rowSums(rcounts)>0),] 
colnames(cnt) <- str_extract(colnames(cnt), "\\d\\d_S\\d\\d|\\d\\d_S\\d")
```

```{r}
coldata <- read.csv2("coldata.csv")
order_cols <- coldata$Sample_ID
cnt <-  cnt[,order_cols]
coldata <- as.matrix(coldata, rownames.force = NA)
rownames(coldata) <- coldata[,1]
dim(cnt)
head(cnt)
```

```{r}
human_biotype_genelength <- read.csv("GCF_000001405.25_GRCh37.tsv", row.names = NULL, sep="\t")

human_biotype <- read.csv("GCF_000001405.39_GRCh38.p13_feature_table.tsv", row.names = NULL, sep="\t")
```

```{r}
coding_genes <- human_biotype %>%
  dplyr::filter(class == "protein_coding" | class == "with_protein")
```

```{r}
cnt <- subset(cnt, rownames(cnt) %in% coding_genes$symbol)
```

```{r}
geneLength <- human_biotype_genelength %>%
  dplyr::filter(X..feature == "mRNA") %>%
  dplyr::select("symbol", "product_length") %>%
  dplyr::filter(!is.na(product_length))%>%
  dplyr::rename("GeneID" = "symbol", "Length" = "product_length") %>%
  group_by(GeneID) %>%
  mutate("Length" = mean(Length)) %>%
  distinct(GeneID, .keep_all = TRUE)
```

```{r}
#make countdata a dataframe
countdata <- data.frame(GeneID=rownames(cnt), cnt, check.names = FALSE)
countdata <- geneLength %>%
  inner_join(countdata) %>%
  mutate(Length=ifelse(Length-75+1>0,Length-75+1,1))

tpm<-countdata %>%
  pivot_longer( cols = (grep("\\d", colnames(countdata))), names_to = "sample", 
                values_to = "cnt") %>% 
  group_by(sample) %>%
  mutate(rpk = cnt/ (Length/1000) , libSize = sum(rpk), tpm = rpk / libSize *1e6 )
```

```{r}
tpm <- tpm %>% mutate( minTPM= min(tpm[tpm>0]), log10TPM = log10(tpm+minTPM))
head(tpm)
```
```{r}
# let's remove columns with intermediate results
tpm <- tpm %>% dplyr::select(-libSize,-rpk,-minTPM)

pdf(file="TPM.pdf")
ggplot(tpm,aes(x=sample,y=log10TPM))+ 
  geom_boxplot()+
  coord_flip()+ 
  ylab(expression(log[10](TPM)))+
  ggtitle("TPM")
dev.off()

```

```{r}
tpm %>% summarise(no.of.genes=sum( tpm>=1 ))
```
```{r}
#the tibble tpm is grouped according to samples, this grouping needs to be removed
tpm2<-tpm %>% 
  ungroup() %>% 
  group_by(GeneID) %>%
  dplyr::filter(sum(tpm<1) < 16)

cnt.tib <- tpm2 %>% 
  dplyr::select(GeneID,sample,cnt) %>% 
  unique %>%
  pivot_wider(names_from = sample, values_from = cnt )

#DEseq wants a count matrix not a tibble
cnt.filt<-as.matrix(cnt.tib[,-1]) 
rownames(cnt.filt)<-cnt.tib$GeneID
write.csv(cnt.filt, "Counts_Filtered.csv")
```

```{r}
pdf(file="TPM2.pdf")
ggplot(tpm2,aes(x=sample,y=log10TPM))+ 
  geom_boxplot()+
  coord_flip()+ 
  ylab(expression(log[10](TPM)))+
  ggtitle("TPM_Filtered")
dev.off()
```

```{r}
all(rownames(coldata) %in% colnames(cnt.filt))
```

```{r}
all(rownames(coldata) == colnames(cnt.filt))
```

```{r}
dds <- DESeqDataSetFromMatrix(countData = cnt,
                              colData = coldata,
                              design = ~Sample_Group)
dds
```

```{r}
#keep <- rowSums(counts(dds)) >= 10
#dds <- dds[keep,]
```

```{r}
dds<- DESeq(dds)
```
```{r}
resultsNames(dds)
```

```{r}
vsd <- vst(dds, blind=FALSE)
vsdMat <- assay(vsd)
```

```{r}
vsdmelted <- melt(vsdMat)

pdf("VSD.pdf")
ggplot(vsdmelted, aes(x=Var2, y=value))+
  geom_boxplot()+
  coord_flip()+
  ylab("Variance stabilized counts")+
  xlab("Sample")+
  ggtitle("VST")
dev.off()
```

```{r}
rlog <- rlog(dds)
rlogMat <- assay(rlog)
rlogmelted <- melt(rlogMat)

pdf("rlog.pdf")
ggplot(rlogmelted, aes(x=Var2, y=value))+
  geom_boxplot()+
  coord_flip()+
  ylab("rlog transformed counts")+
  xlab("Sample")+
  ggtitle("rlog")
dev.off()
```
```{r}
pdf(file="PCA_rlog.pdf", height=6, width=8)
pcaData <- plotPCA(rlog, intgroup=c("Sample_Group", "Mutation_Type"), returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
ggplot(pcaData, aes(PC1, PC2, color=Sample_Group, shape=Mutation_Type)) +
  geom_point(size=3) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  theme(axis.title = element_text(size = 10, face = "bold"))+
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  theme(axis.title = element_text(size = 10, face = "bold"))+
  ggtitle("PCA") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),plot.background = element_blank(), axis.line = element_line(), plot.title = element_text(size=15, face="bold")) +
  geom_text_repel(aes(label=name), size=3, color="black", nudge_y = 1, fontface="bold",  min.segment.length = unit(0, "lines"), max.overlaps = Inf)+
  scale_color_manual(values=c("deeppink3", "yellowgreen", "red3", "darkorange1"))+
  geom_encircle(data=subset(pcaData, Sample_Group=="KO"))+
  geom_encircle(data=subset(pcaData, Sample_Group=="WT"))+
  geom_encircle(data=subset(pcaData, Sample_Group=="KOTGFB"))+
  geom_encircle(data=subset(pcaData, Sample_Group=="WTTGFB"))+
  coord_fixed()
dev.off()
```
```{r}
pdf(file="PCA_vst.pdf", height=6, width=8)
pcaData <- plotPCA(vsd, intgroup=c("Sample_Group", "Mutation_Type"), returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
ggplot(pcaData, aes(PC1, PC2, color=Sample_Group, shape=Mutation_Type)) +
  geom_point(size=3) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  theme(axis.title = element_text(size = 10, face = "bold"))+
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  theme(axis.title = element_text(size = 10, face = "bold"))+
  ggtitle("PCA") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),plot.background = element_blank(), axis.line = element_line(), plot.title = element_text(size=15, face="bold")) +
  geom_text_repel(aes(label=name), size=3, color="black", nudge_y = 1, fontface="bold",  min.segment.length = unit(0, "lines"), max.overlaps = Inf)+
  scale_color_manual(values=c("deeppink3", "yellowgreen", "red3", "darkorange1"))+
  geom_encircle(data=subset(pcaData, Sample_Group=="KO"))+
  geom_encircle(data=subset(pcaData, Sample_Group=="WT"))+
  geom_encircle(data=subset(pcaData, Sample_Group=="KOTGFB"))+
  geom_encircle(data=subset(pcaData, Sample_Group=="WTTGFB"))+
  coord_fixed()
dev.off()
```

```{r}
res_ko_wt <- DESeq2::results(dds, contrast=c("Sample_Group","KO","WT"), alpha = 0.05)
summary(res_ko_wt)
```

```{r}
ko_wt_list<-data.frame(gene = rownames(res_ko_wt), res_ko_wt,
stringsAsFactors = F) %>% na.omit() %>% dplyr::select("log2FoldChange", "padj") %>% dplyr::mutate(minuslogp = -log10(padj), "LFCminuslogp" = log2FoldChange*minuslogp) %>% rownames_to_column(var = "gene")

ko_wt_sorted <- ko_wt_list %>% 
  arrange(desc(abs(LFCminuslogp)))

write.xlsx(ko_wt_sorted, "ko_wt_sorted.xlsx")

pdf(file="Volcano_ko_wt.pdf", width=24, height=21)
ggplot(ko_wt_list, aes(x=log2FoldChange, y=(minuslogp)))+
  geom_point(size=2.25,color="grey", alpha=0.5)+
  geom_point(data=subset(ko_wt_list, minuslogp>(-log10(0.05))), size=2.25,color="darkorange1", alpha=1)+
  geom_point(data=subset(ko_wt_list, minuslogp>(-log10(0.05)) & abs(log2FoldChange)>(1)), size=2.25,color="red3", alpha=1)+
  geom_point(data=subset(ko_wt_list, minuslogp<(-log10(0.05)) & abs(log2FoldChange)>(1)), size=2.25,color="yellowgreen", alpha=1)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),plot.background = element_blank(), axis.line = element_line()) +
  ggtitle("TNIK KO vs WT")+
  theme(plot.title = element_text(size = 60, face = "bold"))+
  xlab("Log2FoldChange")+
  theme(axis.title = element_text(size = 40, face = "bold"), axis.text=element_text(size=20, face = "bold"))+
  ylab("-log10(p-adj)")+
  theme(axis.title = element_text(size = 40, face = "bold"), axis.text=element_text(size=20, face = "bold"))+
  geom_vline(xintercept = 1, linetype="dashed")+
  geom_vline(xintercept = -1, linetype="dashed")+
  geom_hline(yintercept = -log10(0.05), linetype="dashed")+
  geom_label_repel(data=subset(ko_wt_list, minuslogp>(-log10(0.05)) | abs(log2FoldChange)>1), aes(label=gene), size=6, color="black", nudge_y = 0.5, fontface="bold",  min.segment.length = unit(0, "lines"), max.overlaps = 20)
dev.off()

pdf(file="Volcano_ko_wt_validated.pdf", width=24, height=21)
ggplot(ko_wt_list, aes(x=log2FoldChange, y=(minuslogp)))+
  geom_point(size=2.25,color="grey", alpha=0.5)+
  geom_point(data=subset(ko_wt_list, minuslogp>(-log10(0.05))), size=2.25,color="darkorange1", alpha=1)+
  geom_point(data=subset(ko_wt_list, minuslogp>(-log10(0.05)) & abs(log2FoldChange)>(1)), size=2.25,color="red3", alpha=1)+
  geom_point(data=subset(ko_wt_list, minuslogp<(-log10(0.05)) & abs(log2FoldChange)>(1)), size=2.25,color="yellowgreen", alpha=1)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),plot.background = element_blank(), axis.line = element_line()) +
  ggtitle("TNIK KO vs WT")+
  theme(plot.title = element_text(size = 60, face = "bold"))+
  xlab("Log2FoldChange")+
  theme(axis.title = element_text(size = 40, face = "bold"), axis.text=element_text(size=20, face = "bold"))+
  ylab("-log10(p-adj)")+
  theme(axis.title = element_text(size = 40, face = "bold"), axis.text=element_text(size=20, face = "bold"))+
  geom_vline(xintercept = 1, linetype="dashed")+
  geom_vline(xintercept = -1, linetype="dashed")+
  geom_hline(yintercept = -log10(0.05), linetype="dashed")+
  geom_label_repel(data=subset(ko_wt_list, gene %in% validated_genes), aes(label=gene), size=6, color="black", nudge_y = 0.5, fontface="bold",  min.segment.length = unit(0, "lines"), max.overlaps = 20)
dev.off()
```
```{r}
res_ko_wt<-data.frame(rn=rownames(res_ko_wt),res_ko_wt) %>% na.omit()
#make a named vector of P adjusted
ko_wt_gsea <- res_ko_wt$padj 
names(ko_wt_gsea) <- res_ko_wt$rn
ensgEntrez_ko_wt_gsea <- AnnotationDbi::select(org.Hs.eg.db, keys=names(ko_wt_gsea), columns='ENTREZID', keytype='SYMBOL')
df_ko_wt_gsea <- ensgEntrez_ko_wt_gsea %>%
  dplyr::inner_join(res_ko_wt, by=c("SYMBOL"="rn")) %>% 
  dplyr::select(ENTREZID,log2FoldChange,padj) %>% 
  dplyr::group_by(ENTREZID) %>%
  dplyr::summarise(lfc=mean(log2FoldChange), up=min(padj))
ko_wt_lfc<-df_ko_wt_gsea$lfc 
names(ko_wt_lfc)<-df_ko_wt_gsea$ENTREZID

y_ko_wt_reac <- gsePathway(sort((ko_wt_lfc), decreasing=T), organism = "human", pvalueCutoff=0.1, pAdjustMethod="BH", verbose=F)


y_ko_wt_kegg <- gseKEGG(sort((ko_wt_lfc), decreasing=T), organism = "hsa", pvalueCutoff=0.1, pAdjustMethod="BH", verbose=F)

y_ko_wt_go <- gseGO(sort((ko_wt_lfc), decreasing=T), OrgDb=org.Hs.eg.db,
                            ont   = "ALL", pvalueCutoff=0.1, pAdjustMethod="BH", verbose=F)

y_ko_wt_msigdb <- GSEA(sort((ko_wt_lfc), decreasing=T), pvalueCutoff=0.1, pAdjustMethod="BH", verbose=F, TERM2GENE = msigdb)

y_ko_wt_reac <- setReadable(y_ko_wt_reac, 'org.Hs.eg.db', 'ENTREZID')
ko_wt_gsea <- y_ko_wt@result
ko_wt_gsea <- ko_wt_gsea %>% arrange(desc(NES))

pathway_list_ko_wt <- c("Interferon gamma signaling",
                             "Interleukin-10 signaling",
                             "Interferon alpha/beta signaling",
                        "GPCR ligand binding",
                        "Class A/1 (Rhodopsin-like receptors)")

geneSetID_ko_wt = match(pathway_list_ko_wt,
                              y_ko_wt@result[["Description"]])

pdf("gseaplot2_ko_wt.pdf", width=12, height=10)
gseaplot2(y_ko_wt, geneSetID = geneSetID_ko_wt[!is.na(geneSetID_ko_wt)], 
          pvalue_table = FALSE, 
          title="TNIK KO vs WT Selected Pathways", 
          base_size = 18,
          rel_heights = c(2.5,0.3,0.5))+
  theme(axis.text = element_text(size=12, face = "bold"),
        axis.title = element_text(size=16))
dev.off()

pdf("heatplot_ko_wt.pdf", width = 20, height=5)
enrichplot::heatplot(y_ko_wt, 
                     showCategory = pathway_list_ko_wt, 
                     foldChange = ko_wt_lfc)+
  ggtitle("TNIK KO vs WT Selected Pathways")+
  theme(axis.text.y=element_text(size=12, face = "bold"),
        axis.text.x=element_text(size=9, face="bold"),
        plot.title = element_text(size = 24, face="bold"))
dev.off()
```
```{r}
C3_t2g <- msigdbr(species = "Homo sapiens", category = "C2") %>% 
  dplyr::select(gs_name, entrez_gene)
head(C3_t2g)

y_ko_wt_msig_onco <- GSEA(sort((ko_wt_lfc), decreasing=T), pvalueCutoff=0.1, pAdjustMethod="BH", verbose=F, TERM2GENE = C3_t2g)
```

```{r}
res_ko_wt_sig_sort_p <-data.frame(gene = rownames(res_ko_wt), res_ko_wt,
stringsAsFactors = F) %>% 
  na.omit() %>%
  filter(padj<0.05 & log2FoldChange < (-2.0)) %>%
  arrange(padj) %>%
  mutate(minuslogp = -log10(padj), minuslog2p = -log2(padj))

sig_genelist_ko_wt <- res_ko_wt_sig_sort_p$gene

coldata_df <- as.data.frame(coldata)
df <- coldata_df %>% dplyr::select(Sample_Group, Mutation_Type)

rownames(df) <- row.names(coldata)

df <- df %>% dplyr::arrange(Sample_Group)
df_ko_wt <- df %>% dplyr::filter(Sample_Group %in% c("WT","KO"))

vsdMat_ko_wt <- vsdMat[,row.names(df_ko_wt)]

pdf("Heatmap_siglist_ko_wt.pdf", width=14, height = 32)
pheatmap(subset(vsdMat_ko_wt, rownames(vsdMat_ko_wt) %in% sig_genelist_ko_wt), cluster_rows=TRUE, show_rownames=TRUE,cluster_cols=FALSE, annotation_col=df_ko_wt, scale = "row", fontsize = 20, fontsize_col = 25, fontsize_row = 18, angle_col = 90, main="Genes with LFC <(-2.0) & padj<0.05 in KO vs WT")
dev.off()
```
```{r}
signature_database <- read.csv("SignatureDB_030920.tsv", sep = "\t")

signatures <- signature_database %>%
    dplyr::select(X____Short.signature.name, X____Gene.ID.concensus) %>%
    tidyr::unnest()
```

```{r}
sig_enrich_ko_wt <- GSEA(sort((ko_wt_lfc), decreasing=T), TERM2GENE = signatures)
sig_enrich_ko_wt <- setReadable(sig_enrich_ko_wt, 'org.Hs.eg.db', 'ENTREZID')
```

```{r}
res_kotgfb_wttgfb <- DESeq2::results(dds, contrast=c("Sample_Group","KOTGFB","WTTGFB"), alpha = 0.05)
summary(res_kotgfb_wttgfb)
```

```{r}
kotgfb_wttgfb_list<-data.frame(gene = rownames(res_kotgfb_wttgfb), res_kotgfb_wttgfb,
stringsAsFactors = F) %>% na.omit() %>% dplyr::select("log2FoldChange", "padj") %>% dplyr::mutate(minuslogp = -log10(padj), "LFCminuslogp" = log2FoldChange*minuslogp) %>% rownames_to_column(var = "gene")

kotgfb_wttgfb_sorted <- kotgfb_wttgfb_list %>% 
  arrange(desc(abs(LFCminuslogp)))

write.xlsx(kotgfb_wttgfb_sorted, "kotgfb_wttgfb_sorted.xlsx")

pdf(file="Volcano_kotgfb_wttgfb.pdf", width=24, height=21)
ggplot(kotgfb_wttgfb_list, aes(x=log2FoldChange, y=(minuslogp)))+
  geom_point(size=2.25,color="grey", alpha=0.5)+
  geom_point(data=subset(kotgfb_wttgfb_list, minuslogp>(-log10(0.05))), size=2.25,color="darkorange1", alpha=1)+
  geom_point(data=subset(kotgfb_wttgfb_list, minuslogp>(-log10(0.05)) & abs(log2FoldChange)>(1)), size=2.25,color="red3", alpha=1)+
  geom_point(data=subset(kotgfb_wttgfb_list, minuslogp<(-log10(0.05)) & abs(log2FoldChange)>(1)), size=2.25,color="yellowgreen", alpha=1)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),plot.background = element_blank(), axis.line = element_line()) +
  ggtitle("TNIK KO vs WT")+
  theme(plot.title = element_text(size = 60, face = "bold"))+
  xlab("Log2FoldChange")+
  theme(axis.title = element_text(size = 40, face = "bold"), axis.text=element_text(size=20, face = "bold"))+
  ylab("-log10(p-adj)")+
  theme(axis.title = element_text(size = 40, face = "bold"), axis.text=element_text(size=20, face = "bold"))+
  geom_vline(xintercept = 1, linetype="dashed")+
  geom_vline(xintercept = -1, linetype="dashed")+
  geom_hline(yintercept = -log10(0.05), linetype="dashed")+
  geom_label_repel(data=subset(kotgfb_wttgfb_list, minuslogp>(-log10(0.05)) | abs(log2FoldChange)>1), aes(label=gene), size=6, color="black", nudge_y = 0.5, fontface="bold",  min.segment.length = unit(0, "lines"), max.overlaps = 20)
dev.off()

pdf(file="Volcano_kotgfb_wttgfb_validated.pdf", width=24, height=21)
ggplot(kotgfb_wttgfb_list, aes(x=log2FoldChange, y=(minuslogp)))+
  geom_point(size=2.25,color="grey", alpha=0.5)+
  geom_point(data=subset(kotgfb_wttgfb_list, minuslogp>(-log10(0.05))), size=2.25,color="darkorange1", alpha=1)+
  geom_point(data=subset(kotgfb_wttgfb_list, minuslogp>(-log10(0.05)) & abs(log2FoldChange)>(1)), size=2.25,color="red3", alpha=1)+
  geom_point(data=subset(kotgfb_wttgfb_list, minuslogp<(-log10(0.05)) & abs(log2FoldChange)>(1)), size=2.25,color="yellowgreen", alpha=1)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),plot.background = element_blank(), axis.line = element_line()) +
  ggtitle("TNIK KO vs WT")+
  theme(plot.title = element_text(size = 60, face = "bold"))+
  xlab("Log2FoldChange")+
  theme(axis.title = element_text(size = 40, face = "bold"), axis.text=element_text(size=20, face = "bold"))+
  ylab("-log10(p-adj)")+
  theme(axis.title = element_text(size = 40, face = "bold"), axis.text=element_text(size=20, face = "bold"))+
  geom_vline(xintercept = 1, linetype="dashed")+
  geom_vline(xintercept = -1, linetype="dashed")+
  geom_hline(yintercept = -log10(0.05), linetype="dashed")+
  geom_label_repel(data=subset(kotgfb_wttgfb_list, gene %in% validated_genes), aes(label=gene), size=6, color="black", nudge_y = 0.5, fontface="bold",  min.segment.length = unit(0, "lines"), max.overlaps = 20)
dev.off()
```

```{r}
res_kotgfb_wttgfb<-data.frame(rn=rownames(res_kotgfb_wttgfb),res_kotgfb_wttgfb) %>% na.omit()
#make a named vector of P adjusted
kotgfb_wttgfb_gsea <- res_kotgfb_wttgfb$padj 
names(kotgfb_wttgfb_gsea) <- res_kotgfb_wttgfb$rn
ensgEntrez_kotgfb_wttgfb_gsea <- AnnotationDbi::select(org.Hs.eg.db, keys=names(kotgfb_wttgfb_gsea), columns='ENTREZID', keytype='SYMBOL')

df_kotgfb_wttgfb_gsea <- ensgEntrez_kotgfb_wttgfb_gsea %>%
  dplyr::inner_join(res_kotgfb_wttgfb, by=c("SYMBOL"="rn")) %>% 
  dplyr::select(ENTREZID,log2FoldChange,padj) %>% 
  dplyr::group_by(ENTREZID) %>%
  dplyr::summarise(lfc=mean(log2FoldChange), up=min(padj))
kotgfb_wttgfb_lfc<-df_kotgfb_wttgfb_gsea$lfc 
names(kotgfb_wttgfb_lfc)<-df_kotgfb_wttgfb_gsea$ENTREZID

y_kotgfb_wttgfb_reac <- gsePathway(sort((kotgfb_wttgfb_lfc), decreasing=T), organism = "human", pvalueCutoff=0.1, pAdjustMethod="BH", verbose=F)

y_kotgfb_wttgfb_kegg <- gseKEGG(sort((kotgfb_wttgfb_lfc), decreasing=T), organism = "hsa", pvalueCutoff=0.1, pAdjustMethod="BH", verbose=F)

y_kotgfb_wttgfb_go <- gseGO(sort((kotgfb_wttgfb_lfc), decreasing=T), OrgDb=org.Hs.eg.db,
                            ont   = "ALL", pvalueCutoff=0.1, pAdjustMethod="BH", verbose=F)

y_kotgfb_wttgfb <- setReadable(y_kotgfb_wttgfb, 'org.Hs.eg.db', 'ENTREZID')
kotgfb_wttgfb_gsea <- y_kotgfb_wttgfb@result
kotgfb_wttgfb_gsea <- kotgfb_wttgfb_gsea %>% arrange(desc(NES))

pathway_list_kotgfb_wttgfb <- c("Interferon gamma signaling",
                             "Interleukin-10 signaling",
                             "Interferon alpha/beta signaling",
                        "GPCR ligand binding",
                        "Class A/1 (Rhodopsin-like receptors)")

geneSetID_kotgfb_wttgfb = match(pathway_list_kotgfb_wttgfb,
                              y_kotgfb_wttgfb@result[["Description"]])

pdf("gseaplot2_kotgfb_wttgfb.pdf", width=12, height=10)
gseaplot2(y_kotgfb_wttgfb, geneSetID = geneSetID_kotgfb_wttgfb[!is.na(geneSetID_kotgfb_wttgfb)], 
          pvalue_table = FALSE, 
          title="TNIK KO vs WT Selected Pathways", 
          base_size = 18,
          rel_heights = c(2.5,0.3,0.5))+
  theme(axis.text = element_text(size=12, face = "bold"),
        axis.title = element_text(size=16))
dev.off()

pdf("heatplot_kotgfb_wttgfb.pdf", width = 20, height=5)
enrichplot::heatplot(y_kotgfb_wttgfb, 
                     showCategory = pathway_list_kotgfb_wttgfb, 
                     foldChange = kotgfb_wttgfb_lfc)+
  ggtitle("TNIK KO vs WT Selected Pathways")+
  theme(axis.text.y=element_text(size=12, face = "bold"),
        axis.text.x=element_text(size=9, face="bold"),
        plot.title = element_text(size = 24, face="bold"))
dev.off()
```

```{r}
res_kotgfb_wttgfb_sig_sort_p <-data.frame(gene = rownames(res_kotgfb_wttgfb), res_kotgfb_wttgfb,
stringsAsFactors = F) %>% 
  na.omit() %>%
  filter(padj<0.05 & log2FoldChange < (-2.0)) %>%
  arrange(padj) %>%
  mutate(minuslogp = -log10(padj), minuslog2p = -log2(padj))

sig_genelist_kotgfb_wttgfb <- res_kotgfb_wttgfb_sig_sort_p$gene

coldata_df <- as.data.frame(coldata)
df <- coldata_df %>% dplyr::select(Sample_Group, Mutation_Type)

rownames(df) <- row.names(coldata)

df <- df %>% dplyr::arrange(Sample_Group)
df_kotgfb_wttgfb <- df %>% dplyr::filter(Sample_Group %in% c("WT","KO"))

vsdMat_kotgfb_wttgfb <- vsdMat[,row.names(df_kotgfb_wttgfb)]

pdf("Heatmap_siglist_kotgfb_wttgfb.pdf", width=14, height = 32)
pheatmap(subset(vsdMat_kotgfb_wttgfb, rownames(vsdMat_kotgfb_wttgfb) %in% sig_genelist_kotgfb_wttgfb), cluster_rows=TRUE, show_rownames=TRUE,cluster_cols=FALSE, annotation_col=df_kotgfb_wttgfb, scale = "row", fontsize = 20, fontsize_col = 25, fontsize_row = 18, angle_col = 90, main="Genes with LFC <(-2.0) & padj<0.05 in KO vs WT")
dev.off()
```

